blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/nathanm82/tessera/discussions
    about: For open-ended questions, please use Discussions instead of issues.
